import '../imports/client/routes'
import '../imports/client/common/landingLayout.html'
import '../imports/client/common/workLayout.html'
import '../imports/client/common/header.html'
import '../imports/client/common/header.js'
import '../imports/client/common/footer.html'
import '../imports/client/common/signIn.html'
import '../imports/client/common/signIn.js'
import '../imports/client/common/newAccount.html'
import '../imports/client/common/newAccount.js'

import '../imports/client/teams/teamList.html'
import '../imports/client/teams/teamList.js'
