import './teamList.html'
import './teamList.js'
import './newTeam.html'
import './newTeam.js'
import './teamListItem.html'
import './teamListItem.js'
import './teamMenu.html'
import './teamMenu.js'
import './manageTeam.html'
import './manageTeam.js'
import './teamSubItems.html'
import './teamMembers.html'
import './teamMembers.js'
import './memberItem.html'
import './memberItem.js'

