import './publications/publication-teams'
import './publications/publication-userPreferences'
import './publications/publication-teamMembers'
import './publications/publication-organizationMembers'
import './publications/publication-membership'
import './publications/publication-organizations'

import './methods/method-addUserToOrg'
import './methods/method-addTeamTech'
import './methods/method-removeTeamTech'
import './methods/method-addTeamRole'
import './methods/method-removeTeamRole'
import './methods/method-addTeam'
import './methods/method-updateTeam'
import './methods/method-addOrganization'
import './methods/method-setUserPreferences'
import './methods/method-inviteOrganizationMember'
import './methods/method-unInviteOrganizationMember'
import './methods/method-userEnrollment'
import './methods/method-teamMemberAdd'
import './methods/method-teamMemberRemove'

import './utils/startup'
